# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(502, 457)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(502, 457))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(213, 281))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 235, 279))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.textBoxLog = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBoxLog.setMinimumSize(QtCore.QSize(231, 121))
        self.textBoxLog.setObjectName("textBoxLog")
        self.gridLayout_3.addWidget(self.textBoxLog, 1, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(241, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_9 = QtWidgets.QLabel(self.tab_7)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_9.setObjectName("label_9")
        self.inputFGDir = QtWidgets.QLineEdit(self.tab_7)
        self.inputFGDir.setGeometry(QtCore.QRect(10, 30, 181, 20))
        self.inputFGDir.setObjectName("inputFGDir")
        self.btnFGDir = QtWidgets.QToolButton(self.tab_7)
        self.btnFGDir.setGeometry(QtCore.QRect(200, 30, 31, 21))
        self.btnFGDir.setObjectName("btnFGDir")
        self.label_10 = QtWidgets.QLabel(self.tab_7)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_10.setObjectName("label_10")
        self.inputSimTime = QtWidgets.QLineEdit(self.tab_7)
        self.inputSimTime.setGeometry(QtCore.QRect(10, 80, 181, 20))
        self.inputSimTime.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.inputSimTime.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.inputSimTime.setObjectName("inputSimTime")
        self.label_11 = QtWidgets.QLabel(self.tab_7)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 81, 16))
        self.label_11.setObjectName("label_11")
        self.inputSimTimeStep = QtWidgets.QLineEdit(self.tab_7)
        self.inputSimTimeStep.setGeometry(QtCore.QRect(10, 130, 181, 20))
        self.inputSimTimeStep.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputSimTimeStep.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.inputSimTimeStep.setObjectName("inputSimTimeStep")
        self.label_12 = QtWidgets.QLabel(self.tab_7)
        self.label_12.setGeometry(QtCore.QRect(0, 350, 231, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_7)
        self.label_13.setGeometry(QtCore.QRect(0, 370, 101, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_7)
        self.label_14.setGeometry(QtCore.QRect(200, 80, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_7)
        self.label_15.setGeometry(QtCore.QRect(200, 130, 47, 13))
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_4 = QtWidgets.QLabel(self.tab_6)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_4.setObjectName("label_4")
        self.inputParams = QtWidgets.QLineEdit(self.tab_6)
        self.inputParams.setGeometry(QtCore.QRect(10, 30, 181, 20))
        self.inputParams.setObjectName("inputParams")
        self.btnChoseParamDir = QtWidgets.QToolButton(self.tab_6)
        self.btnChoseParamDir.setGeometry(QtCore.QRect(200, 30, 31, 21))
        self.btnChoseParamDir.setObjectName("btnChoseParamDir")
        self.label_5 = QtWidgets.QLabel(self.tab_6)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.label_5.setObjectName("label_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_6)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 100, 153, 78))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 151, 76))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_6 = QtWidgets.QLabel(self.tab_6)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.btnStartFG = QtWidgets.QPushButton(self.tab_5)
        self.btnStartFG.setGeometry(QtCore.QRect(10, 131, 221, 23))
        self.btnStartFG.setObjectName("btnStartFG")
        self.btnConnect = QtWidgets.QPushButton(self.tab_5)
        self.btnConnect.setGeometry(QtCore.QRect(10, 160, 221, 23))
        self.btnConnect.setObjectName("btnConnect")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 221, 16))
        self.label_3.setObjectName("label_3")
        self.listAircraft = QtWidgets.QComboBox(self.tab_5)
        self.listAircraft.setGeometry(QtCore.QRect(10, 30, 221, 20))
        self.listAircraft.setObjectName("listAircraft")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 40, 16))
        self.label_2.setObjectName("label_2")
        self.listAirport = QtWidgets.QComboBox(self.tab_5)
        self.listAirport.setGeometry(QtCore.QRect(10, 90, 221, 20))
        self.listAirport.setObjectName("listAirport")
        self.btnStart = QtWidgets.QPushButton(self.tab_5)
        self.btnStart.setGeometry(QtCore.QRect(10, 300, 221, 23))
        self.btnStart.setObjectName("btnStart")
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Software name V0.1"))
        self.label.setText(_translate("MainWindow", "aircraft.png"))
        self.label_9.setText(_translate("MainWindow", "FlightGear Path"))
        self.btnFGDir.setText(_translate("MainWindow", "..."))
        self.label_10.setText(_translate("MainWindow", "Time of Simulation"))
        self.label_11.setText(_translate("MainWindow", "TimeStep"))
        self.label_12.setText(_translate("MainWindow", " Always remeber to press enter in the textbox"))
        self.label_13.setText(_translate("MainWindow", " to save the settings"))
        self.label_14.setText(_translate("MainWindow", "s"))
        self.label_15.setText(_translate("MainWindow", "s"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Configuration"))
        self.label_4.setText(_translate("MainWindow", "Select Parameters File"))
        self.btnChoseParamDir.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "Or"))
        self.label_7.setText(_translate("MainWindow", "Cl:"))
        self.label_8.setText(_translate("MainWindow", "Cd:"))
        self.label_6.setText(_translate("MainWindow", "Set Manually"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Parameters"))
        self.btnStartFG.setText(_translate("MainWindow", "Start FlightGear"))
        self.btnConnect.setText(_translate("MainWindow", "Connect with FlightGear"))
        self.label_3.setText(_translate("MainWindow", "Airport:"))
        self.label_2.setText(_translate("MainWindow", "Aircraft:"))
        self.btnStart.setText(_translate("MainWindow", "Start Simulation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Simulation"))
